alias ga="git add"
alias gc="git commit -m"
alias gp="git push"
alias gpl="git pull"
alias gs="git status"
alias gsl="git status | less"
alias gl="git log"
alias glog="git log --oneline"
alias gsu="git status --untracked-files=no"
alias gsh="git status | head -n"