alias ga="git add"
alias gc="git commit -m"
alias gp="git push"
alias gpl="git pull"
alias gs="git status"
alias gsl="git status | less"
alias gl="git log"
alias gsu="git status --untracked-files=no"
alias gsh="git status | head -n"
alias gr="git remote"
alias grv="git remote -v"
alias gb="git branch"
alias gba="git branch -a"
alias glog='git log --decorate --pretty=format:"%C(auto)%h %C(cyan)%d %C(green)%ad %s" --date=format:"%Y-%m-%d %H:%M:%S"'